services:
  web1:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./logs/web1:/App/Logs
  web2:
    build: .
    ports:
      - "8081:80"
    volumes:
      - ./logs/web2:/App/Logs
  web3:
    build: .
    ports:
      - "8082:80"
    volumes:
      - ./logs/web3:/App/Logs